In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
file2 = "drive/MyDrive/iris_1e2.csv"
file3 = "drive/MyDrive/iris_1e3.csv"

import os
returnValue = os.path.isfile(file2)
print(returnValue)
returnValue2 = os.path.isfile(file3)
print(returnValue2)

True
True


In [ ]:
import pandas as pd
import numpy as np

data2 = pd.read_csv(file2 , header=None)
data3 = pd.read_csv(file3 , header=None)

print(data2)
print(data3)

                  0    1    2
0   Iris versicolor  4.7  1.4
1   Iris versicolor  4.5  1.5
2   Iris versicolor  4.9  1.5
3   Iris versicolor  4.0  1.3
4   Iris versicolor  4.6  1.5
..              ...  ...  ...
95   Iris virginica  5.2  2.3
96   Iris virginica  5.0  1.9
97   Iris virginica  5.2  2.0
98   Iris virginica  5.4  2.3
99   Iris virginica  5.1  1.8

[100 rows x 3 columns]
                   0    1    2
0    Iris versicolor  3.4  1.1
1    Iris versicolor  3.7  1.4
2    Iris versicolor  3.4  0.9
3    Iris versicolor  3.8  1.2
4    Iris versicolor  4.3  1.4
..               ...  ...  ...
995   Iris virginica  5.3  2.0
996   Iris virginica  6.0  2.2
997   Iris virginica  5.4  2.1
998   Iris virginica  5.7  2.1
999   Iris virginica  6.2  2.1

[1000 rows x 3 columns]


Seperating Labels and Features


In [ ]:
print(type(data2))

column0 = data2.__getitem__(0)

column0row18 = column0.__getitem__(18)
column0row78 = column0.__getitem__(78)
print(column0row78)

column0_2 = data2[0]
column0row78_2 = column0_2[78]
print(column0row78_2)

print(data2[0][78])
print (type(data2[0]))

<class 'pandas.core.frame.DataFrame'>
Iris virginica
Iris virginica
Iris virginica
<class 'pandas.core.series.Series'>


In [ ]:
from sklearn.preprocessing import LabelEncoder

labels2 = data2[0].to_numpy()
print(labels2)
print(type(labels2))

encoder = LabelEncoder()
encoder.fit(labels2)
labels2binary = encoder.transform(labels2)
print(labels2binary)

['Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris versicolor' 'Iris versicolor'
 'Iris versicolor' 'Iris versicolor' 'Iris virginica' 'Iris virginica'
 'Iris virginica' 'Iris virginica' 'Iris virginica' '

In [ ]:
columns1and2_file2 = data2.drop(0,axis=1)
print(columns1and2_file2)

feautures2 = columns1and2_file2.to_numpy()
print(feautures2)


      1    2
0   4.7  1.4
1   4.5  1.5
2   4.9  1.5
3   4.0  1.3
4   4.6  1.5
..  ...  ...
95  5.2  2.3
96  5.0  1.9
97  5.2  2.0
98  5.4  2.3
99  5.1  1.8

[100 rows x 2 columns]
[[4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]
 [4.6 1.4]
 [4.  1.2]
 [3.3 1. ]
 [4.2 1.3]
 [4.2 1.2]
 [4.2 1.3]
 [4.3 1.3]
 [3.  1.1]
 [4.1 1.3]
 [6.  2.5]
 [5.1 1.9]
 [5.9 2.1]
 [5.6 1.8]
 [5.8 2.2]
 [6.6 2.1]
 [4.5 1.7]
 [6.3 1.8]
 [5.8 1.8]
 [6.1 2.5]
 [5.1 2. ]
 [5.3 1.9]
 [5.5 2.1]
 [5.  2. ]
 [5.1 2.4]
 [5.3 2.3]
 [5.5 1.8]
 [6.7 2.2]
 [6.9 2.3]
 [5.  1.5]
 [5.7 2.3]
 [4.9 2. ]
 [6.7 2. ]
 [4.9 1.8]
 [5.7 

In [ ]:
labels3 = data3[0].to_numpy()
features3 = data3.drop(0,axis=1).to_numpy()
labels3binary = encoder.transform(labels3)
print(labels3binary)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

For Loops

In [ ]:
sequence = np.array( [1 ,2 ,3 ,4 ,5 ])
for changing in[0 , 1, 2, 3, 4]:
    print(sequence[changing]*3)


3
6
9
12
15


Something about Numpy

In [ ]:
print(sequence[:])
print(feautures2[15][0])
print(feautures2[15,0])

[1 2 3 4 5]
4.4
4.4


True False Arrays

In [ ]:
array = np.array([True , False , True , False , True])
print(array)
print(type(array))
print(sequence)

[ True False  True False  True]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
trueFalseArray = (sequence> 2.5)
print(trueFalseArray)

[False False  True  True  True]


In [ ]:
nonzeroindexes = trueFalseArray.nonzero()[0]


In [ ]:
print(len(nonzeroindexes))

3


In [ ]:
sequence = np.array([1 , 2, 3,4 ,5])
nonzeroindexes = (sequence>3.5).nonzero()[0]
print(len(nonzeroindexes))

2


Look for the best Decision Boundary

In [ ]:
lengths = feautures2[ : , 0]
widths = feautures2[:,1]

print(lengths)
print(widths)

lengths3 = features3[ : , 0]
widths3 = features3[:,1]

[4.7 4.5 4.9 4.  4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1
 4.5 3.9 4.8 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5
 4.7 4.4 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6
 5.8 6.6 4.5 6.3 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9
 6.7 4.9 5.7 6.  4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4
 5.6 5.1 5.1 5.9 5.7 5.2 5.  5.2 5.4 5.1]
[1.4 1.5 1.5 1.3 1.5 1.3 1.6 1.  1.3 1.4 1.  1.5 1.  1.4 1.3 1.4 1.5 1.
 1.5 1.1 1.8 1.3 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.  1.1 1.  1.2 1.6 1.5 1.6
 1.5 1.3 1.3 1.3 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8
 2.2 2.1 1.7 1.8 1.8 2.5 2.  1.9 2.1 2.  2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.
 2.  1.8 2.1 1.8 1.8 1.8 2.1 1.6 1.9 2.  2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1
 2.4 2.3 1.9 2.3 2.5 2.3 1.9 2.  2.3 1.8]


In [ ]:
minvalue = lengths.min()
possibleBoundaries = np.arange(lengths.min() , lengths.max()+0.15 , step=0.1)
for boundary in possibleBoundaries:

  virginica_pred =  (lengths >= boundary).nonzero()[0]
  virginca_true = (virginica_pred >= 50).nonzero()[0]

  versicolour_pred =  (lengths < boundary).nonzero()[0]
  versicolour_true = (versicolour_pred <= 49).nonzero()[0]

  accuracy = (len(virginca_true) + len(versicolour_true))
  print("At" , boundary.round(1) , "accuracy is" , accuracy)
  #calculating the accuracy values

At 3.0 accuracy is 50
At 3.1 accuracy is 51
At 3.2 accuracy is 51
At 3.3 accuracy is 53
At 3.4 accuracy is 53
At 3.5 accuracy is 55
At 3.6 accuracy is 56
At 3.7 accuracy is 57
At 3.8 accuracy is 58
At 3.9 accuracy is 61
At 4.0 accuracy is 66
At 4.1 accuracy is 69
At 4.2 accuracy is 73
At 4.3 accuracy is 75
At 4.4 accuracy is 79
At 4.5 accuracy is 85
At 4.6 accuracy is 88
At 4.7 accuracy is 93
At 4.8 accuracy is 93
At 4.9 accuracy is 92
At 5.0 accuracy is 90
At 5.1 accuracy is 84
At 5.2 accuracy is 82
At 5.3 accuracy is 80
At 5.4 accuracy is 78
At 5.5 accuracy is 75
At 5.6 accuracy is 69
At 5.7 accuracy is 66
At 5.8 accuracy is 63
At 5.9 accuracy is 61
At 6.0 accuracy is 59
At 6.1 accuracy is 56
At 6.2 accuracy is 56
At 6.3 accuracy is 55
At 6.4 accuracy is 54
At 6.5 accuracy is 54
At 6.6 accuracy is 53
At 6.7 accuracy is 51
At 6.8 accuracy is 51
At 6.9 accuracy is 50
At 7.0 accuracy is 50


In [ ]:
print(type(False))
print(type(0))

constructedInt = int(False)
print(constructedInt)
print(int(True))

<class 'bool'>
<class 'int'>
0
1


In [ ]:
possibleBoundaries = np.arange(lengths.min() , lengths.max()+0.15 , step=0.1)

for boundary in possibleBoundaries:

  predictions =  np.array ((lengths >= boundary) , dtype = int)
  accuracy = len((predictions == labels2binary).nonzero()[0])
  print( "at" , boundary.round(1) , "How well do they match up/ accuracy is " , accuracy)
  #calculating the accuracy values

at 3.0 How well do they match up/ accuracy is  50
at 3.1 How well do they match up/ accuracy is  51
at 3.2 How well do they match up/ accuracy is  51
at 3.3 How well do they match up/ accuracy is  53
at 3.4 How well do they match up/ accuracy is  53
at 3.5 How well do they match up/ accuracy is  55
at 3.6 How well do they match up/ accuracy is  56
at 3.7 How well do they match up/ accuracy is  57
at 3.8 How well do they match up/ accuracy is  58
at 3.9 How well do they match up/ accuracy is  61
at 4.0 How well do they match up/ accuracy is  66
at 4.1 How well do they match up/ accuracy is  69
at 4.2 How well do they match up/ accuracy is  73
at 4.3 How well do they match up/ accuracy is  75
at 4.4 How well do they match up/ accuracy is  79
at 4.5 How well do they match up/ accuracy is  85
at 4.6 How well do they match up/ accuracy is  88
at 4.7 How well do they match up/ accuracy is  93
at 4.8 How well do they match up/ accuracy is  93
at 4.9 How well do they match up/ accuracy is  92


In [ ]:
from sklearn.metrics import accuracy_score

possibleBoundaries = np.arange(lengths.min() , lengths.max()+0.15 , step=0.1)

for boundary in possibleBoundaries:

  train_predictions =  np.array ((lengths >= boundary) , dtype = int)
  train_accuracy = accuracy_score(labels2binary , train_predictions)

  test_predictions = np.array ( ( lengths3 >= boundary), dtype=int)
  test_accuracy = accuracy_score(labels3binary , test_predictions)
  print( "at" , boundary.round(1) , "training" ,train_accuracy , "Test" , test_accuracy)
  #calculating the accuracy values

at 3.0 training 0.5 Test 0.5
at 3.1 training 0.51 Test 0.501
at 3.2 training 0.51 Test 0.503
at 3.3 training 0.53 Test 0.514
at 3.4 training 0.53 Test 0.521
at 3.5 training 0.55 Test 0.53
at 3.6 training 0.56 Test 0.54
at 3.7 training 0.57 Test 0.556
at 3.8 training 0.58 Test 0.583
at 3.9 training 0.61 Test 0.614
at 4.0 training 0.66 Test 0.654
at 4.1 training 0.69 Test 0.689
at 4.2 training 0.73 Test 0.728
at 4.3 training 0.75 Test 0.762
at 4.4 training 0.79 Test 0.791
at 4.5 training 0.85 Test 0.837
at 4.6 training 0.88 Test 0.865
at 4.7 training 0.93 Test 0.896
at 4.8 training 0.93 Test 0.912
at 4.9 training 0.92 Test 0.907
at 5.0 training 0.9 Test 0.899
at 5.1 training 0.84 Test 0.882
at 5.2 training 0.82 Test 0.862
at 5.3 training 0.8 Test 0.827
at 5.4 training 0.78 Test 0.8
at 5.5 training 0.75 Test 0.767
at 5.6 training 0.69 Test 0.735
at 5.7 training 0.66 Test 0.705
at 5.8 training 0.63 Test 0.664
at 5.9 training 0.61 Test 0.623
at 6.0 training 0.59 Test 0.595
at 6.1 training 0